import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      firstName: 'Mythili',
      lastName: 'sivasamy',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      resetToken: '',
    },
    {
      firstName: 'Mahi',
      lastName: 'samy',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      resetToken: '',
    },
  ],
  products: [
    {
      name: 'Lilliput casuals',
      slug: 'lilliput-casuals-1',
      category: 'Casuals',
      image: './images/kids/casual-1.jpg',
      price: 350,
      countInStock: 10,
      brand: 'Lilliput',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Max Ethnic1',
      slug: 'max-ethnic-1',
      category: 'Ethnic',
      image: './images/kids/ethnic-1.jpg',
      price: 2350,
      countInStock: 10,
      brand: 'Max',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Max Ethnic2',
      slug: 'max-ethnic-2',
      category: 'Ethnic',
      image: './images/kids/ethnic-2.jpg',
      price: 1450,
      countInStock: 10,
      brand: 'Max',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Max Ethnic3',
      slug: 'max-ethnic-3',
      category: 'Ethnic',
      image: './images/kids/ethnic-3.jpg',
      price: 1350,
      countInStock: 10,
      brand: 'Max',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Max Ethnic4',
      slug: 'max-ethnic-4',
      category: 'Ethnic',
      image: './images/kids/ethnic-4.jpg',
      price: 1100,
      countInStock: 10,
      brand: 'Max',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Lilliput Casuals2',
      slug: 'lilliput-casuals-2',
      category: 'Casuals',
      image: './images/kids/casual-2.jpg',
      price: 250,
      countInStock: 10,
      brand: 'Lilliput',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Lilliput Casuals3',
      slug: 'lilliput-casuals-3',
      category: 'Casuals',
      image: './images/kids/casual-3.jpg',
      price: 300,
      countInStock: 10,
      brand: 'Lilliput',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Lilliput Casuals4',
      slug: 'lilliput-casuals-4',
      category: 'Casuals',
      image: './images/kids/casual-4.jpg',
      price: 450,
      countInStock: 10,
      brand: 'Lilliput',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Silk Sarees1',
      slug: 'silk-saree-1',
      category: 'saree',
      image: './images/women/saree-1.jpg',
      price: 2890,
      countInStock: 10,
      brand: 'pantalooms',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Silk Sarees2',
      slug: 'silk-saree-2',
      category: 'saree',
      image: './images/women/saree-2.jpg',
      price: 1890,
      countInStock: 10,
      brand: 'pantalooms',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Cotton Sarees3',
      slug: 'Cotton-saree-3',
      category: 'saree',
      image: './images/women/saree-3.jpg',
      price: 890,
      countInStock: 10,
      brand: 'pantalooms',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Cotton Sarees4',
      slug: 'cotton-saree-4',
      category: 'saree',
      image: './images/women/saree-4.jpg',
      price: 650,
      countInStock: 0,
      brand: 'pantalooms',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Kurtha1',
      slug: 'kurtha-1',
      category: 'kurtha',
      image: './images/women/kurtha-1.jpg',
      price: 1250,
      countInStock: 20,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Kurtha2',
      slug: 'kurtha-2',
      category: 'kurtha',
      image: './images/women/kurtha-2.jpg',
      price: 950,
      countInStock: 5,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Kurtha3',
      slug: 'kurtha-3',
      category: 'kurtha',
      image: './images/women/kurtha-3.jpg',
      price: 750,
      countInStock: 0,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Kurtha4',
      slug: 'kurtha-4',
      category: 'kurtha',
      image: './images/women/kurtha-4.jpg',
      price: 1750,
      countInStock: 10,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality Dresses',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirt',
      image: './images/men/casual-1.jpg',
      price: 500,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Indian Terrain Shirt',
      slug: 'indian-terrain-shirt',
      category: 'Shirt',
      image: './images/men/casual-2.jpg',
      price: 425,
      countInStock: 15,
      brand: 'Indian Terrain',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Max Shirt',
      slug: 'Max-shirt',
      category: 'Shirt',
      image: './images/men/casual-3.jpg',
      price: 2065,
      countInStock: 5,
      brand: 'Max',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Allen Solly Shirt',
      slug: 'Allen-Solly-shirt',
      category: 'Shirt',
      image: './images/men/casual-6.jpg',
      price: 2065,
      countInStock: 5,
      brand: 'Allen Solly',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Peter England Shirt',
      slug: 'Peter England-shirt',
      category: 'Shirt',
      image: './images/men/casual-7.jpg',
      price: 2065,
      countInStock: 5,
      brand: 'Peter England',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Trends T-Shirt1',
      slug: 'trends-t-shirt-1',
      category: 'Shirt',
      image: './images/men/t-shirt-2.jpg',
      price: 350,
      countInStock: 5,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Trends T-Shirt2',
      slug: 'trends-t-shirt-2',
      category: 'Shirt',
      image: './images/men/t-shirt-3.jpg',
      price: 550,
      countInStock: 5,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Trends T-Shirt3',
      slug: 'trends-t-shirt-3',
      category: 'Shirt',
      image: './images/men/t-shirt-6.jpg',
      price: 650,
      countInStock: 0,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Trends T-Shirt4',
      slug: 'trends-t-shirt-4',
      category: 'Shirt',
      image: './images/men/t-shirt-8.jpg',
      price: 650,
      countInStock: 5,
      brand: 'Trends',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

  ],
};
export default data;
/*


*/
